# ----------------------------------------------------------------
# Dockerfile used for dev
#
# Author: Christopher Wagner
# ----------------------------------------------------------------

# ----------------------------------------------------------------
# Build Stage
# ----------------------------------------------------------------

FROM node:latest as build

WORKDIR /usr/src/app

COPY . .

RUN npm install



# ----------------------------------------------------------------
# Serve Stage
# ----------------------------------------------------------------

FROM node:16-alpine3.11

RUN apk add dumb-init

RUN apk --no-cache add --virtual builds-deps build-base python

WORKDIR /usr/src/app

COPY --chown=node:node --from=build /usr/src/app/ /usr/src/app/

RUN npm i -g @nestjs/cli

USER node

CMD ["dumb-init", "nest", "start", "--watch"]

EXPOSE 3000