version: '3.8'

services:
  dev-postgres:
    image: postgres
    restart: always
    env_file:
      - ../environment-variables/.db.dev.env
    ports:
      - '5432:5432'
  
  dev-pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ../environment-variables/.db.dev.env
    ports:
      - '8080:80'